backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/static/media"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "blog_post.html"}
      - {label: "Date", name: "date", widget: "date"}
      - {body: "Body", name: "body", widget: "markdown"}
      
